// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "friendship-projecttcc",
            "region": "us-east-1"
        },
        {
            "tableName": "routes-projecttcc",
            "region": "us-east-1"
        },
        {
            "tableName": "getRoute-projecttcc",
            "region": "us-east-1"
        },
        {
            "tableName": "ShareTracking-projecttcc",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "Friendship",
            "endpoint": "https://hlghwmx6kc.execute-api.us-east-1.amazonaws.com/projecttcc",
            "region": "us-east-1"
        },
        {
            "name": "Routes",
            "endpoint": "https://zd4arxhm6f.execute-api.us-east-1.amazonaws.com/projecttcc",
            "region": "us-east-1"
        },
        {
            "name": "getRoute",
            "endpoint": "https://snsp6w9y8d.execute-api.us-east-1.amazonaws.com/projecttcc",
            "region": "us-east-1"
        },
        {
            "name": "ShareTracking",
            "endpoint": "https://5qk6zikmr9.execute-api.us-east-1.amazonaws.com/projecttcc",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:eed50d98-3922-4744-b4f4-e9cc2543af59",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RolZfAffo",
    "aws_user_pools_web_client_id": "6hbbphfth1hmpefndc63i20fae",
    "oauth": {},
    "GOOGLEAPI": "AIzaSyBNWlA0LdrEMFEww_o6_tWGltDG2kS5I_Y"
};


export default awsmobile;
